# -*- coding: utf-8 -*-
"""Student Activity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O0LDIcycCr1K5iZyKuZJBcf7uWF7vBwC
"""

print("Ini adalah student Activity")